
;;;;;;;;;;;;;;;;;;;;;;;;;; BLUETOOTH-LCD USART CARRO Y COMANDOS ;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F10
    CBLOCK  0X20
	T1, T2
	ALM, CURSOR
	CUENTA
	INDICE,LETRA
	SAV_H,SAV_L
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
#DEFINE	RS  PORTA,0
#DEFINE	EN  PORTA,1
    ORG	0X0000
    GOTO CONFIGU
    ORG	0X0004
    GOTO INTERRUPCION
 
CONFIGU:
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    BSF	    PCON,OSCF
    MOVLW   B'00000010'
    MOVWF   TRISB
    BCF	    TRISA,0
    BCF	    TRISA,1
    BCF	    TRISA,2
    BCF	    TRISA,3
    BCF	    TRISA,6
    BCF	    TRISA,7
    BANK0
    CLRF    PORTB
    CLRF    PORTA
CONF_INTERUPCIONES:
    BSF	    INTCON,GIE
    BSF	    INTCON,PEIE
    BANK1
    BSF	    PIE1,RCIE
CONF_LCD:
    BANK0
    MOVLW   .10
    CALL    MILIS
    MOVLW   0X32
    CALL    ENV_CMD
    MOVLW   0X28
    CALL    ENV_CMD
    MOVLW   0X0D;EN PARPADEO, 0X0C SIN PARPADEO
    CALL    ENV_CMD
    MOVLW   0X06
    CALL    ENV_CMD
    MOVLW   0X01
    CALL    ENV_CMD
CONF_USART:
    MOVLW   .255;TIEMPO PARA EL BLUETOOTH
    CALL    MILIS
    BSF	    RCSTA,SPEN
    BANK1
    MOVLW   B'00000100';TRANSMISION APAGADA
    MOVWF   TXSTA
    MOVLW   .25
    MOVWF   SPBRG
    BANK0
    MOVLW   B'11001000'
    MOVWF   RCSTA
    BSF	    RCSTA,CREN
    ;MENSAJE DE INICIO
    MOVLW   0X80
    CALL    ENV_CMD
    CLRF    INDICE
M1: BSF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X100, PAGINA=1
    CALL    MEN_INICIO
    BCF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X000, PAGINA=0
    MOVWF   LETRA
    XORLW   .0
    BTFSC   STATUS,Z
    GOTO    INICIO
    MOVF    LETRA,W
    CALL    ENV_CAR
    INCF    INDICE,F
    GOTO    M1
    
INICIO:
    SLEEP
    GOTO    INICIO
    
INTERRUPCION:
    BCF	    PIR1,RCIF    
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    MOVF    RCREG,W
    XORLW   "8"
    BTFSC   STATUS,Z
    GOTO    RUN
    MOVF    RCREG,W
    XORLW   "4"
    BTFSC   STATUS,Z
    GOTO    LEFT
    MOVF    RCREG,W
    XORLW   "6"
    BTFSC   STATUS,Z
    GOTO    RIGHT
    MOVF    RCREG,W
    XORLW   "5"
    BTFSC   STATUS,Z
    GOTO    STOP
    MOVF    RCREG,W
    XORLW   "2"
    BTFSC   STATUS,Z
    GOTO    BACK
    RETFIE
RUN:
    MOVLW   B'10000100'
    MOVWF   PORTA
    MOVLW   0X01
    CALL    ENV_CMD
    MOVLW   0X80
    CALL    ENV_CMD
    CLRF    INDICE
M2: BSF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X100, PAGINA=1
    CALL    MEN_RUN
    BCF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X000, PAGINA=0
    MOVWF   LETRA
    XORLW   .0
    BTFSC   STATUS,Z
    RETFIE
    MOVF    LETRA,W
    CALL    ENV_CAR
    INCF    INDICE,F
    GOTO    M2
    
STOP:
    MOVLW   B'00000000'
    MOVWF   PORTA
    MOVLW   0X01
    CALL    ENV_CMD
    MOVLW   0X80
    MOVWF   CURSOR
    CLRF    INDICE
M3: MOVF    CURSOR,W
    CALL    ENV_CMD
    BSF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X100, PAGINA=1
    CALL    MEN_STOP
    BCF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X000, PAGINA=0
    MOVWF   LETRA
    XORLW   .0
    BTFSC   STATUS,Z
    RETFIE
    MOVF    LETRA,W
    CALL    ENV_CAR
    INCF    INDICE,F
    INCF    CURSOR,F
    MOVF    CURSOR,W
    XORLW   0X90
    BTFSS   STATUS,Z
    GOTO    M3
    MOVLW   0XC0
    MOVWF   CURSOR
    GOTO    M3
    
BACK:
    MOVLW   B'01001000'
    MOVWF   PORTA
    MOVLW   0X01
    CALL    ENV_CMD
    MOVLW   0X80
    CALL    ENV_CMD
    CLRF    INDICE
M4: BSF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X100, PAGINA=1
    CALL    MEN_BACK
    BCF	    PCLATH,0	;REDIRECCIONAMIENTO A POSICION 0X000, PAGINA=0
    MOVWF   LETRA
    XORLW   .0
    BTFSC   STATUS,Z
    RETFIE
    MOVF    LETRA,W
    CALL    ENV_CAR
    INCF    INDICE,F
    GOTO    M4
    
LEFT:
    BCF	    PORTA,2
    BCF	    PORTA,3
    MOVLW   .255
    CALL    MILIS
    BTFSS   PORTA,7
    GOTO    S1
    GOTO    S2
S1  BCF	    PORTA,2
    BSF	    PORTA,3
    RETFIE
S2  BSF	    PORTA,2
    BCF	    PORTA,3
    RETFIE
    
RIGHT:
    BCF	    PORTA,7
    BCF	    PORTA,6
    MOVLW   .255
    CALL    MILIS
    BTFSS   PORTA,2
    GOTO    S3
    GOTO    S4
S3  BCF	    PORTA,7
    BSF	    PORTA,6
    RETFIE
S4  BSF	    PORTA,7
    BCF	    PORTA,6
    RETFIE
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    #INCLUDE "LIBRERIA.INC"
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ORG 0X100
MEN_INICIO:
    MOVF    INDICE,W
    ADDWF   PCL,F
    DT	"      HOLA      ",.0
    
MEN_RUN:
    MOVF    INDICE,W
    ADDWF   PCL,F
    DT	"      GO!!!     ",.0
MEN_STOP:
    MOVF    INDICE,W
    ADDWF   PCL,F
    DT	"    ESPERANDO   "
    DT	"  INSTRUCCIONES ",.0
MEN_BACK:
    MOVF    INDICE,W
    ADDWF   PCL,F
    DT	" CUIDADO BICAS  ",.0 

    
    END 
    
    
    
;;;;;;;;;;;;;;;;;;;;;;;;;; BLUETOOTH-LCD USART FINAL ESCRITURA Y COMANDOS ;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F10
    CBLOCK  0X20
	T1, T2
	ALM, CURSOR
	CUENTA, TESTEO
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
#DEFINE	RS  PORTA,0
#DEFINE	EN  PORTA,1
    ORG	0X0000
    GOTO CONFIGU
    
    ORG	0X0005
CONFIGU:
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    BSF	    PCON,OSCF
    MOVLW   B'00000010'
    MOVWF   TRISB
    BCF	    TRISA,0
    BCF	    TRISA,1
    BCF	    TRISA,2
    BANK0
    CLRF    PORTB
    CLRF    PORTA
CONF_LCD:
    ;EL LCD POSEES FUNCIONES DE DESPLAZAMIENTOS
    ;PERO VAN DE 0X80-0XA7 SON COMO 40 POSICIONES 
    ;EN LA PRIMERA LINEA DEL LCD
    ;DE AHI TIENES QUE VOLVER A REDIRIGIR C0
    MOVLW   .10
    CALL    MILIS
    MOVLW   0X32
    CALL    ENV_CMD
    MOVLW   0X28
    CALL    ENV_CMD
    MOVLW   0X0D;EN PARPADEO, 0X0C SIN PARPADEO
    CALL    ENV_CMD
    MOVLW   0X06
    CALL    ENV_CMD
    MOVLW   0X01
    CALL    ENV_CMD
    BSF	    PORTA,2
    MOVLW   .255
    CALL    MILIS
CONF_USART:
    ;CONFIG DEL USART
    BSF	    RCSTA,SPEN
    BANK1
    MOVLW   B'00000100';TRANSMISION APAGADA
    MOVWF   TXSTA
    MOVLW   .25
    MOVWF   SPBRG
    BANK0
    MOVLW   B'11001000'
    MOVWF   RCSTA
    BSF	    RCSTA,CREN
    MOVLW   0X80
    MOVWF   CURSOR
INICIO:
    BANK0
    BTFSS   PIR1,RCIF
    GOTO    $-1
    BCF	    PIR1,RCIF
    
    MOVF    CURSOR,W
    XORLW   0X7F
    BTFSC   STATUS,Z
    GOTO    I1
    MOVF    CURSOR,W
    XORLW   0XA8
    BTFSC   STATUS,Z
    GOTO    I3
    MOVF    CURSOR,W
    XORLW   0XBF
    BTFSC   STATUS,Z
    GOTO    I2
    MOVF    CURSOR,W
    XORLW   0XE8
    BTFSC   STATUS,Z
    GOTO    I4
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    MOVF    RCREG,W
    XORLW   .9
    BTFSC   STATUS,Z
    GOTO    DELETE
    MOVF    RCREG,W
    XORLW   "6"
    BTFSC   STATUS,Z
    GOTO    ROTA_DE
    MOVF    RCREG,W
    XORLW   "4"
    BTFSC   STATUS,Z
    GOTO    ROTA_IZ
    MOVF    RCREG,W
    XORLW   .0
    BTFSC   STATUS,Z
    GOTO    TURN_OFF
    MOVF    RCREG,W
    XORLW   .1
    BTFSC   STATUS,Z
    GOTO    TURN_ON
    MOVF    RCREG,W
    XORLW   .7
    BTFSC   STATUS,Z
    GOTO    CLEAR_ALL
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    MOVF    CURSOR,W
    CALL    ENV_CMD
    MOVF    RCREG,W
    CALL    ENV_CAR
    
    MOVF    RCREG,W
    XORLW   .228
    BTFSC   STATUS,Z
    GOTO    RETRO
    INCF    CURSOR,F
    GOTO    INICIO
    
;LA APLICACION ENVIA DOS DATOS
;UNO DE ELLOS ES UN DATOS EXTRA
;QUE NO QUEREMOS MOSTRAR EN EL LCD
RETRO
    MOVLW   0X10    ;REGRESA UN ESPACIO A LA IZQUIERDA
    CALL    ENV_CMD 
    MOVLW   " "	    ;"BORRA" LA LETRA ANTERIOR
    CALL    ENV_CAR
    MOVLW   0X10    
    CALL    ENV_CMD 
    DECF    CURSOR,F
    GOTO    INICIO
    
I1  MOVLW   0X80
    MOVWF   CURSOR
    GOTO    INICIO
I2  MOVLW   0XA7
    MOVWF   CURSOR
    GOTO    INICIO
I3  MOVLW   0XC0
    MOVWF   CURSOR
    GOTO    INICIO
I4  MOVLW   0XE7
    MOVWF   CURSOR
    GOTO    INICIO
    
DELETE:
    MOVLW   0X10    ;REGRESA UN ESPACIO A LA IZQUIERDA
    CALL    ENV_CMD 
    MOVLW   " "	    ;"BORRA" LA LETRA ANTERIOR
    CALL    ENV_CAR
    MOVLW   0X10    
    CALL    ENV_CMD 
    DECF    CURSOR,F
    GOTO    INICIO
ROTA_DE:
    MOVLW   0X1C    ;DESPLAZAMIENTO A LA DERECHA
    CALL    ENV_CMD ;UN POSICION
    GOTO    INICIO
ROTA_IZ:
    MOVLW   0X18    ;DESPLAZAMIENTO A LA IZQUIERDA
    CALL    ENV_CMD
    GOTO    INICIO
TURN_OFF:
    MOVLW   0X09    ;LCD APAGADO
    CALL    ENV_CMD ;PERO AUN SE´PUEDE ESCRIBIR
    GOTO    INICIO  ;NO SE MUESTRA,PERO SE ESTA ESCRIBIENDO
TURN_ON:
    MOVLW   0X0D
    CALL    ENV_CMD
    GOTO    INICIO
CLEAR_ALL:
    MOVLW   0X01
    CALL    ENV_CMD
    MOVLW   0X80
    MOVWF   CURSOR
    GOTO    INICIO    

#INCLUDE "LIBRERIA.INC"
    END
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; USART RECEPTOR BLUETOOTH ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;PIN=1234
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F10
    CBLOCK  0X20
    T1,T2,ALM
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
#DEFINE	RS  PORTA,0
#DEFINE	EN  PORTA,1
    ORG	0X0000
    GOTO CONFIGU
    
    ORG	0X0005
CONFIGU
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    BSF	    PCON,OSCF
    MOVLW   B'00000010'
    MOVWF   TRISB
    BCF	    TRISA,0
    BCF	    TRISA,1
    BCF	    TRISA,2
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    BSF	    PORTA,2
    MOVLW   .255
    CALL    MILIS
    ;CONFIG DEL USART
    BSF	    RCSTA,SPEN
    BANK1
    MOVLW   B'00000100';TRANSMISION APAGADA
    MOVWF   TXSTA
    MOVLW   .25;4MHZ
    MOVWF   SPBRG
    BANK0
    MOVLW   B'11001000'
    MOVWF   RCSTA
    BSF	    RCSTA,CREN
INICIO
    BANK0
    BTFSS   PIR1,RCIF
    GOTO    $-1
    BCF	    PIR1,RCIF
    MOVF    RCREG,W
    XORLW   "A"	;0X0D=ENTER
    BTFSS   STATUS,Z
    GOTO    INICIO
    BTFSS   PORTB,0
    GOTO    S1
    GOTO    S2
    
S1  BSF	    PORTB,0
    GOTO    INICIO
S2  BCF	    PORTB,0
    GOTO    INICIO
    #INCLUDE "LIBRERIA.INC"
    END
    
;;;;;;;;;;;;;;;;;;;;;;;;;; USART RECEPTOR DE PALABRAS ;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F10
    CBLOCK  0X20
	T1, T2
	ALM, CURSOR
	CUENTA, TESTEO
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
#DEFINE	RS  PORTA,0
#DEFINE	EN  PORTA,1
    ORG	0X0000
    GOTO CONFIGU
    
    ORG	0X0005
CONFIGU:
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    MOVLW   B'00000010'
    MOVWF   TRISB
    BCF	    TRISA,0
    BCF	    TRISA,1
    BCF	    TRISA,2
    BANK0
    CLRF    PORTB
    CLRF    PORTA
CONF_LCD:
    ;EL LCD POSEES FUNCIONES DE DESPLAZAMIENTOS
    ;PERO VAN DE 0X80-0XA7 SON COMO 40 POSICIONES 
    ;EN LA PRIMERA LINEA DEL LCD
    ;DE AHI TIENES QUE VOLVER A REDIRIGIR C0
    MOVLW   .10
    CALL    MILIS
    MOVLW   0X32
    CALL    ENV_CMD
    MOVLW   0X28
    CALL    ENV_CMD
    MOVLW   0X0D;EN PARPADEO, 0X0C SIN PARPADEO
    CALL    ENV_CMD
    MOVLW   0X06
    CALL    ENV_CMD
    MOVLW   0X01
    CALL    ENV_CMD
    BSF	    PORTA,2
    MOVLW   .255
    CALL    MILIS
CONF_USART:
    ;CONFIG DEL USART
    BSF	    RCSTA,SPEN
    BANK1
    MOVLW   B'00000100';TRANSMISION APAGADA
    MOVWF   TXSTA
    MOVLW   .129
    MOVWF   SPBRG
    BANK0
    MOVLW   B'11001000'
    MOVWF   RCSTA
    BSF	    RCSTA,CREN
    MOVLW   0X80
    MOVWF   CURSOR
INICIO:
    BANK0
    BTFSS   PIR1,RCIF
    GOTO    $-1
    BCF	    PIR1,RCIF
    
    MOVF    RCREG,W
    XORLW   0X08    ;ATRAS
    BTFSC   STATUS,Z
    GOTO    DELETE
    
    MOVF    RCREG,W
    XORLW   "+"    
    BTFSC   STATUS,Z
    GOTO    ROTA_DE
    
    MOVF    RCREG,W
    XORLW   "-"    
    BTFSC   STATUS,Z
    GOTO    ROTA_IZ
    
    MOVF    RCREG,W
    XORLW   0X09    ;TAB
    BTFSC   STATUS,Z
    GOTO    TURN_OFF
    
    MOVF    RCREG,W
    XORLW   "|"	    ;ARRIBA DE TAB
    BTFSC   STATUS,Z
    GOTO    TURN_ON
    
    MOVF    RCREG,W
    XORLW   0X0D    ;ENTER
    BTFSC   STATUS,Z
    GOTO    CLEAR_ALL
    
    MOVF    CURSOR,W
    CALL    ENV_CMD
    MOVF    RCREG,W
    CALL    ENV_CAR
    INCF    CURSOR,F
    
    MOVF    CURSOR,W
    XORLW   0X7F
    BTFSC   STATUS,Z
    GOTO    I1
    MOVF    CURSOR,W
    XORLW   0X90
    BTFSC   STATUS,Z
    GOTO    I3
    MOVF    CURSOR,W
    XORLW   0XBF
    BTFSC   STATUS,Z
    GOTO    I2
    MOVF    CURSOR,W
    XORLW   0XD0
    BTFSC   STATUS,Z
    GOTO    I4
    
    GOTO    INICIO
    
I1  MOVLW   0X80
    MOVWF   CURSOR
    GOTO    INICIO
I2  MOVLW   0X8F
    MOVWF   CURSOR
    GOTO    INICIO
I3  MOVLW   0XC0
    MOVWF   CURSOR
    GOTO    INICIO
I4  MOVLW   0XCF
    MOVWF   CURSOR
    GOTO    INICIO
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;   
DELETE:
    MOVLW   0X10    ;REGRESA UN ESPACIO A LA IZQUIERDA
    CALL    ENV_CMD 
    MOVLW   " "	    ;"BORRA" LA LETRA ANTERIOR
    CALL    ENV_CAR
    MOVLW   0X10    
    CALL    ENV_CMD 
    DECF    CURSOR,F
    GOTO    INICIO  
    
ROTA_DE:
    MOVLW   0X1C    ;DESPLAZAMIENTO A LA DERECHA
    CALL    ENV_CMD ;UN POSICION
    GOTO    INICIO
ROTA_IZ:
    MOVLW   0X18    ;DESPLAZAMIENTO A LA IZQUIERDA
    CALL    ENV_CMD
    GOTO    INICIO
    
TURN_OFF:
    MOVLW   0X09    ;LCD APAGADO
    CALL    ENV_CMD ;PERO AUN SE´PUEDE ESCRIBIR
    GOTO    INICIO  ;NO SE MUESTRA,PERO SE ESTA ESCRIBIENDO
TURN_ON:
    MOVLW   0X0D
    CALL    ENV_CMD
    GOTO    INICIO
    
CLEAR_ALL:
    MOVLW   0X01
    CALL    ENV_CMD
    MOVLW   0X80
    MOVWF   CURSOR
    ;CALL    ENV_CMD
    GOTO    INICIO

DERECHA     ;NO SIRVE
    MOVLW   0X14
    CALL    ENV_CMD
    GOTO    INICIO
IZQUIERDA   ;NO SIRVE
    MOVLW   0X10    
    CALL    ENV_CMD 
    GOTO    INICIO 
    
#INCLUDE "LIBRERIA.INC"
    END
 
;;;;;;;;;;;;;;;;;;;;;;;;;; USART RECEPTOR DE PALABRAS ;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F10
    CBLOCK  0X20
	CUENTA,TESTEO
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
#DEFINE	RS  PORTA,0
#DEFINE	EN  PORTA,1
    ORG	0X0000
    GOTO CONFIGU
    
    ORG	0X0005
CONFIGU
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    MOVLW   B'00000010'
    MOVWF   TRISB
    BCF	    TRISA,0
    BCF	    TRISA,1
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    ;CONFIG DEL USART
    BSF	    RCSTA,SPEN
    BANK1
    MOVLW   B'00000100';TRANSMISION APAGADA
    MOVWF   TXSTA
    MOVLW   .129
    MOVWF   SPBRG
    BANK0
    MOVLW   B'11001000'
    MOVWF   RCSTA
    BSF	    RCSTA,CREN
INICIO
    BANK0
    BTFSS   PIR1,RCIF
    GOTO    $-1
    BCF	    PIR1,RCIF
    
    MOVF    TESTEO,W
    XORLW   B'00000000'
    BTFSC   STATUS,Z
    GOTO    L1
    
    MOVF    TESTEO,W
    XORLW   B'00000001'
    BTFSC   STATUS,Z
    GOTO    L2
    
    MOVF    TESTEO,W
    XORLW   B'00000011'
    BTFSC   STATUS,Z
    GOTO    L3
    
    MOVF    TESTEO,W
    XORLW   B'00000111'
    BTFSC   STATUS,Z
    GOTO    L4
    
    MOVF    TESTEO,W
    XORLW   B'00001111'
    BTFSC   STATUS,Z
    GOTO    ENTER
    GOTO    INICIO
    
    
L1  MOVF    RCREG,W
    XORLW   "H"	;0X0D=ENTER
    BTFSS   STATUS,Z
    GOTO    S3
    BSF	    TESTEO,0
    GOTO    INICIO
    
L2  MOVF    RCREG,W
    XORLW   "O"	;0X0D=ENTER
    BTFSS   STATUS,Z
    GOTO    S3
    BSF	    TESTEO,1
    GOTO    INICIO
    
L3  MOVF    RCREG,W
    XORLW   "L"	;0X0D=ENTER
    BTFSS   STATUS,Z
    GOTO    S3
    BSF	    TESTEO,2
    GOTO    INICIO
    
L4  MOVF    RCREG,W
    XORLW   "A"	;0X0D=ENTER
    BTFSS   STATUS,Z
    GOTO    S3
    BSF	    TESTEO,3
    GOTO    INICIO
    
ENTER
    MOVF    RCREG,W
    XORLW   0X0D ;0X0D=ENTER,0X20=ESPACIO
    BTFSS   STATUS,Z
    GOTO    S3
    BTFSS   PORTB,0
    GOTO    S1
    GOTO    S2
    
S1  CLRF    TESTEO
    BSF	    PORTB,0
    GOTO    INICIO
S2  CLRF    TESTEO
    BCF	    PORTB,0
    GOTO    INICIO
S3  CLRF    TESTEO
    GOTO    INICIO
;#INCLUDE "LIBRERIA.INC"
    END
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; USART RECEPTOR ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  
    
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; USART TRANSMISOR ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F10
    CBLOCK  0X20
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
#DEFINE	RS  PORTA,0
#DEFINE	EN  PORTA,1
    ORG	0X0000
    GOTO CONFIGU
    
    ORG	0X0005
CONFIGU
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    MOVLW   B'00000010'
    MOVWF   TRISB
    BCF	    TRISA,0
    BCF	    TRISA,1
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    ;CONFIG DEL USART
    BSF	    RCSTA,SPEN
    BANK1
    MOVLW   B'00000100';TRANSMISION APAGADA
    MOVWF   TXSTA
    MOVLW   .129
    MOVWF   SPBRG
    BANK1
    BSF	    TXSTA,TXEN
INICIO
    BANK0
    MOVLW   "H"
    MOVWF   TXREG
    BTFSS   PIR1,TXIF;NECESITA TIEMPO PARA TRANSMITIR
    GOTO    $-1
    BCF	    PIR1,TXIF
    
    ;BTFSS   TXREG,TRMT	NECESITA TIEMPO PARA TRANSMITIR
    ;GOTO   $-1
    ;BCF     TXREG,TRMT
    
    MOVLW   "O"
    MOVWF   TXREG
    BTFSS   PIR1,TXIF
    GOTO    $-1
    BCF	    PIR1,TXIF
    MOVLW   "L"
    MOVWF   TXREG
    BTFSS   PIR1,TXIF
    GOTO    $-1
    BCF	    PIR1,TXIF
    MOVLW   "A"
    MOVWF   TXREG
    BTFSS   PIR1,TXIF
    GOTO    $-1
    BCF	    PIR1,TXIF
    GOTO    $	;FIN
    GOTO    INICIO
    END
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; lcd ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F10
    CBLOCK  0X20
	T1,T2
	ALM
	LETRAS,CON_LE
	TECLA,COL
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
#DEFINE	RS  PORTA,0
#DEFINE	EN  PORTA,1
    ORG	0X0000
    GOTO CONFIGU
    
    ORG	0X0005
CONFIGU
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    MOVLW   B'00001111'
    MOVWF   TRISB
    BCF	    TRISA,0
    BCF	    TRISA,1
    BANK0
    CLRF    PORTB
    CLRF    PORTA
CONF_LCD
    MOVLW   .10
    CALL    MILIS
    MOVLW   0X32
    CALL    ENV_CMD
    MOVLW   0X28
    CALL    ENV_CMD
    MOVLW   0X0C
    CALL    ENV_CMD
    MOVLW   0X06
    CALL    ENV_CMD
    MOVLW   0X01
    CALL    ENV_CMD

INICIO
S1  ;MENSAJE
    MOVLW   0X80
    CALL    ENV_CMD
    CLRF    CON_LE
S2
    CALL    MEN_INICIO
    MOVWF   LETRAS
    XORLW   .0
    BTFSC   STATUS,Z
    GOTO    S3
    MOVF    LETRAS,W
    CALL    ENV_CAR
    INCF    CON_LE,F
    GOTO    S2
    
S3  ;MENSAJE
    MOVLW   0XC0
    CALL    ENV_CMD
    INCF    CON_LE,F
S4
    CALL    MEN_INICIO
    MOVWF   LETRAS
    XORLW   .0
    BTFSC   STATUS,Z
    GOTO    S5
    MOVF    LETRAS,W
    CALL    ENV_CAR
    INCF    CON_LE,F
    GOTO    S4
;VERIFICADOR
S5
    MOVLW   0XF0
    MOVWF   PORTB
    MOVF    PORTB,W
    ANDLW   B'00001111'
    BTFSC   STATUS,Z
    GOTO    S5
    MOVLW   0X01
    CALL    ENV_CMD
    MOVLW   0X80
    CALL    ENV_CMD
;TECLADO    
S6
    MOVLW   0X80
    CALL    ENV_CMD
S7  CALL    TECLADO
    MOVWF   TECLA
    SUBLW   0
    BZ	    S7
    MOVF    TECLA,W
    CALL    MEN_TECLA
    CALL    ENV_CAR
    GOTO    S6
    
    GOTO    INICIO
    ;;;;;;;;;;;;;;;;;;;;

TECLADO
    MOVLW   B'11110000'
    MOVWF   PORTB
    MOVF    PORTB,W
    ANDLW   B'00001111'
    BTFSC   STATUS,Z
    RETLW   .0
    MOVLW   B'00010000'
    MOVWF   COL
    MOVLW   .1
    MOVWF   TECLA
S_COL
    COMF    COL,W
    MOVWF   PORTB
    BTFSS   PORTB,0
    GOTO    F1
    BTFSS   PORTB,1
    GOTO    F2
    BTFSS   PORTB,2
    GOTO    F3
    BTFSS   PORTB,3
    GOTO    F4
    RLF	    COL,F
    INCF    TECLA,F
    BTFSS   STATUS,C
    GOTO    S_COL
    RETLW   0
F1  MOVF    TECLA,W
    RETURN
F2  MOVF    TECLA,W
    ADDLW   .4
    RETURN
F3  MOVF    TECLA,W
    ADDLW   .8
    RETURN
F4  MOVF    TECLA,W
    ADDLW   .12
    RETURN
    
MEN_INICIO
    MOVF    CON_LE,W
    ADDWF   PCL,F
    DT	"HELLO",.0,"HOW ARE YOU?",.0

MEN_TECLA
    MOVF    TECLA,W
    ADDWF   PCL,F
    DT	.0,"123A456B789C*0#D"
    
#INCLUDE "LIBRERIA.INC"
    END
    
    
    
    
    
    
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; INTERRUPCION EEPROM ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F02
    
    CBLOCK  0X20
	T1,T2,T3
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
    
    ORG	0X0000
    GOTO CONFIGU

    ORG 0X0004
    GOTO INTERRUPCION
    
CONFIGU
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    MOVLW   B'00000100'
    MOVWF   TRISB
    MOVLW   0x90
    MOVWF   TRISA
    MOVLW   B'10100111';INTERRUPCION EN RB0
    MOVWF   OPTION_REG
    MOVLW   B'11000000'
    MOVWF   INTCON
    BSF	    PIE1,EEIE
    MOVLW   .0
    MOVWF   EEDATA
    MOVLW   .0
    MOVWF   EEADR
INICIO
    CALL    EEPROM
    GOTO    INICIO
    
EEPROM
    BANK1
    BSF	    EECON1, WREN
    MOVLW   0X55 
    MOVWF   EECON2 
    MOVLW   0XAA 
    MOVWF   EECON2
    BSF	    EECON1,WR
    SLEEP
    RETURN
INTERRUPCION
    BANK0
    BCF	    PIR1,EEIF
    BANK1
    INCF    EEDATA,F
    INCF    EEADR,F
    BCF	    EECON1,WREN
    RETFIE
    END
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; INTERRUPCION EEPROM ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    LIST P=16F628A
    #INCLUDE "P16F628A.INC"
    __CONFIG 0x3F02
    
    CBLOCK  0X20
	T1,T2,T3
    ENDC
#DEFINE BANK0 BCF STATUS,RP0
#DEFINE BANK1 BSF STATUS,RP0
    
    ORG	0X0000
    GOTO CONFIGU

    ORG 0X0004
    GOTO INTERRUPCION
    
CONFIGU
    BANK0
    CLRF    PORTB
    CLRF    PORTA
    MOVLW   0X07
    MOVWF   CMCON
    BANK1
    MOVLW   B'00000100'
    MOVWF   TRISB
    MOVLW   0x90
    MOVWF   TRISA
    MOVLW   B'10100111';INTERRUPCION EN RB0
    MOVWF   OPTION_REG
    MOVLW   B'11000000'
    MOVWF   INTCON
    BSF	    PIE1,EEIE
    MOVLW   .0
    MOVWF   EEDATA
    MOVLW   .0
    MOVWF   EEADR
    BANK0
    CLRF    PORTB
INICIO
    ;BANK0
;BT  BTFSS   PORTB,2
    ;GOTO    BT
    BANK1
    BSF	    EECON1, WREN
    MOVLW   0X55 
    MOVWF   EECON2 
    MOVLW   0XAA 
    MOVWF   EECON2
    BSF	    EECON1,WR
    SLEEP
    GOTO    INICIO
;   LAS INTERRUCIONES SON COMO UNA SUBRUTINA
;PERO NO SE NECESITAN CALL
;ADEMAS NECESITAS PONER A CERO LAS BANDERAS
;Y SE PUEDEN UTILIZAR DENTRO DE OTRO CALL
;   SE DESPIERTA DEL SLEEP 
;PERO TE MANDA AL VECTOR INTERRUPCION
;   PONER RETFIE AL FINAL DE LA INTERRUPCION
;RECORDAR LOS BANCO DE MEMORIA
INTERRUPCION
    BANK0
    BCF	    PIR1,EEIF
    BANK1
    INCF    EEDATA,F
    INCF    EEADR,F
    BCF	    EECON1,WREN
    RETFIE
    END